-- local name = "json";
-- vim.lsp.config[name] = {
--   cmd = { "json-lsp", "--stdio" },
--   filetypes = { "json" },
--   settings = {
--     json = {
--       format = {
--         enable = true,
--       },
--     },
--   },
-- }
--
-- vim.lsp.enable(name)
